### ISSUE TITLE
Help with BackBlast Please!

### ISSUE THREAD

**Issue by Calvin2077** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#64]
Hello 

I was wondering if I could please have some help in an error I am getting for BackBlast. I am trying to run the example data provided  in the folder using the line

 python ~/BackBLAST/BackBLAST.py queryGeneList.faa CP000431.1.faa AL123456.3.faa

 but I keep getting the error "_csv.Error: iterator should return strings, not bytes (the file should be opened in text mode)"

Before this error, I first make a blast database using 
makeblastdb -in AL123456.3.faa -dbtype prot
makeblastdb -in CP000431.1.faa -dbtype prot

next I concatenate all the protein sequences using cat *.faa > queryGeneList.faa

I installed both Bio-python and Blast and have tried to the instructions from this post https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/issues/8

If you are curious here is the rest of my coding error i get 

 python ~/BackBLAST/BackBLAST.py queryGeneList.faa CP000431.1.faa AL123456.3.faa
Opening AL123456.3.faa...
>> Forward Blasting to subject proteome...
Traceback (most recent call last):
  File "/Winnebago/cacornel/BackBLAST/BackBLAST.py", line 124, in <module>
    BLASTForward = filterBLASTCSV(BLASTForward)  # Filters BLAST results by percent identity.
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Winnebago/cacornel/BackBLAST/BackBLAST.py", line 70, in filterBLASTCSV
    for HSP in BLASTreader:
_csv.Error: iterator should return strings, not bytes (the file should be open

**Comment by jmtsuji** [comment]
Hello @Calvin2077 

Thanks for trying out BackBLAST! It sounds like you are using the master branch, which contains old code. Might you consider trying the develop branch instead? E.g., release [v2.0.0-alpha6](https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/releases#:~:text=jmtsuji-,v2.0.0%2Dalpha6,-7a57b1b)?

This will have more up-to-date code and help instructions.

If you want to use the full BackBLAST pipeline, see installation instructions in the README file of the develop branch.

Otherwise, if you just want to use the reciprocal BLAST search feature, it's possible to skip a full install and just use the `scripts/search.py` executable. Run (`./search.py -h`) from within the `scripts` folder in an environment with BLAST and BioPython installed. You'll get a help message that will show you how to use the script.

Hope this helps!
Jackson

**Comment by jmtsuji** [comment]
Closing due to inactivity -- feel free to reopen this issue if ever needed.
